# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design\ui_files\scheme.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Scheme(object):
    def setupUi(self, Scheme):
        Scheme.setObjectName("Scheme")
        Scheme.resize(580, 560)
        Scheme.setMinimumSize(QtCore.QSize(580, 560))
        Scheme.setMaximumSize(QtCore.QSize(580, 560))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("design\\ui_files\\../pictures/needle_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Scheme.setWindowIcon(icon)
        Scheme.setStyleSheet("QWidget\n"
"{\n"
"background-color: rgb(255, 243, 244);\n"
"}")
        self.pic_label = QtWidgets.QLabel(Scheme)
        self.pic_label.setGeometry(QtCore.QRect(10, 30, 560, 520))
        self.pic_label.setMaximumSize(QtCore.QSize(560, 520))
        self.pic_label.setText("")
        self.pic_label.setPixmap(QtGui.QPixmap("design\\ui_files\\../pictures/scheme.png"))
        self.pic_label.setScaledContents(True)
        self.pic_label.setObjectName("pic_label")
        self.header = QtWidgets.QLabel(Scheme)
        self.header.setGeometry(QtCore.QRect(10, 9, 560, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.header.setFont(font)
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")

        self.retranslateUi(Scheme)
        QtCore.QMetaObject.connectSlotsByName(Scheme)

    def retranslateUi(self, Scheme):
        _translate = QtCore.QCoreApplication.translate
        Scheme.setWindowTitle(_translate("Scheme", "Схема станка"))
        self.header.setText(_translate("Scheme", "Схематичное изображение параметров и осей станка"))
